# Generated by Django 4.2.6 on 2023-10-30 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reviw",
            new_name="Review",
        ),
    ]
