source:
  data_base_type: mongodb
  host: localhost
  port: 27017
  schema: tina_db
  collection: movies

destination:
  data_base_type: mysql # mysql, csv
  host: localhost
  user: dbadmin
  password: washywashy
  port: 3306
  schema: tests
  table: mongo_movies

pump:
  batch_size: 500
  on_error: stop # stop, skip