source:
  data_base_type: mysql # mysql, csv
  host: localhost
  port: 3306
  schema: tests
  table: movies
destination:
  data_base_type: mongodb
  host: localhost
  port: 2710
  schema: tests
  collection: movies
pump:
  batch_size: 500
  on_error: stop # stop, skip