source:
  data_base_type: csv # mysql, csv
  location: /home/tina/Documents/python/python-tests/Learning-Python/practice-yaml/upstream/business-employment-2022-quarter.csv

destination:
  data_base_type: csv # mysql, csv
  location: /home/tina/Documents/python/python-tests/Learning-Python/practice-yaml/downstream/processed-business-employment-2022-quarter.csv

pump:
  batch_size: 781
  on_error: stop # stop, skip